#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

DOTLY_SETTINGS_PATH=${2:-"${DOTFILES_PATH}/os/ubuntu/settings"}

##? Some defaults utils to view your changes, import and export.
##? Optional params path_to and path_from will be replaced by
##? your "$DOTFILES_PATH/os/mac/settings" folder
##?
##? Usage:
##?   defaults export [<path_to>]
##?   defaults import [<path_from>]
docs::parse "$@"

case $1 in
"export")
  export_plist_path="${DOTLY_SETTINGS_PATH}"
  [[ -d "$export_plist_path" ]] || mkdir -p "$export_plist_path"
  apt list --installed | cut -d"/" -f1 > "${export_plist_path}/apt.plist"
  snap list | tail -n+2 | tr -s " " | cut -f1 -d " " > "${export_plist_path}/snap.plist"
  ;;
"import")
  import_plist_path="${DOTLY_SETTINGS_PATH}"

  if [[ -d "$import_plist_path" ]]; then
    for plist in "${import_plist_path}"/snap.plist; do
      for pkgName in $(cat $plist)
      do
        sudo snap install $pkgName
      done
        echo "Reinstalled all snap packages."
    done

    for plist in "${import_plist_path}"/apt.plist; do
      for pkgName in $(cat $plist)
      do
        sudo apt-get install -y $pkgName
      done
        echo "Reinstalled all apt packages."
    done
  fi
  ;;
*)
  exit 1
  ;;
esac
